import unittest
from linked_list import LinkedList


class LinkedListTest(unittest.TestCase):

    def test_append(self):
        my_linked_list = LinkedList()
        self.assertEqual(my_linked_list.length, 0)
        self.assertIsNone(my_linked_list.head)
        self.assertIsNone(my_linked_list.tail)
        my_linked_list.append(4)
        self.assertEqual(my_linked_list.length, 1)
        self.assertEqual(my_linked_list.head.value, 4)
        self.assertEqual(my_linked_list.tail.value, 4)
        my_linked_list.append(9)
        self.assertEqual(my_linked_list.length, 2)
        self.assertEqual(my_linked_list.head.value, 4)
        self.assertEqual(my_linked_list.tail.value, 9)

    def test_pop(self):
        my_linked_list = LinkedList()
        number = my_linked_list.pop()
        self.assertEqual(my_linked_list.length, 0)
        self.assertIsNone(my_linked_list.head)
        self.assertIsNone(my_linked_list.tail)
        self.assertIsNone(number)
        my_linked_list.append(20)
        my_linked_list.append(30)
        self.assertEqual(my_linked_list.length, 2)
        self.assertEqual(my_linked_list.head.value, 20)
        self.assertEqual(my_linked_list.tail.value, 30)
        number = my_linked_list.pop()
        self.assertEqual(my_linked_list.length, 1)
        self.assertEqual(my_linked_list.head.value, 20)
        self.assertEqual(my_linked_list.tail.value, 20)
        self.assertEqual(number, 30)
        number = my_linked_list.pop()
        self.assertEqual(my_linked_list.length, 0)
        self.assertIsNone(my_linked_list.head)
        self.assertIsNone(my_linked_list.tail)
        self.assertEqual(number, 20)

    def test_prepend(self):
        my_linked_list = LinkedList()
        my_linked_list.prepend(3)
        self.assertEqual(my_linked_list.length, 1)
        self.assertEqual(my_linked_list.head.value, 3)
        self.assertEqual(my_linked_list.tail.value, 3)
        my_linked_list = LinkedList(5)
        self.assertEqual(my_linked_list.length, 1)
        self.assertEqual(my_linked_list.head.value, 5)
        self.assertEqual(my_linked_list.tail.value, 5)
        my_linked_list.prepend(6)
        self.assertEqual(my_linked_list.length, 2)
        self.assertEqual(my_linked_list.head.value, 6)
        self.assertEqual(my_linked_list.tail.value, 5)

    def test_pop_first(self):
        my_linked_list = LinkedList()
        number = my_linked_list.pop_first()
        self.assertEqual(my_linked_list.length, 0)
        self.assertIsNone(my_linked_list.head)
        self.assertIsNone(my_linked_list.tail)
        self.assertIsNone(number)
        my_linked_list.append(20)
        my_linked_list.append(30)
        self.assertEqual(my_linked_list.length, 2)
        self.assertEqual(my_linked_list.head.value, 20)
        self.assertEqual(my_linked_list.tail.value, 30)
        number = my_linked_list.pop_first()
        self.assertEqual(my_linked_list.length, 1)
        self.assertEqual(my_linked_list.head.value, 30)
        self.assertEqual(my_linked_list.tail.value, 30)
        self.assertEqual(number, 20)
        number = my_linked_list.pop_first()
        self.assertEqual(my_linked_list.length, 0)
        self.assertIsNone(my_linked_list.head)
        self.assertIsNone(my_linked_list.tail)
        self.assertEqual(number, 30)

    def test_get(self):
        my_linked_list = LinkedList()
        number = my_linked_list.get(0)
        self.assertEqual(my_linked_list.length, 0)
        self.assertIsNone(my_linked_list.head)
        self.assertIsNone(my_linked_list.tail)
        self.assertIsNone(number)
        number = my_linked_list.get(3)
        self.assertIsNone(number)
        my_linked_list.append(10)
        number = my_linked_list.get(1)
        self.assertIsNone(number)
        my_linked_list.append(20)
        my_linked_list.append(30)
        number = my_linked_list.get(1)
        self.assertEqual(number, 20)
        number = my_linked_list.get(0)
        self.assertEqual(number, 10)
        number = my_linked_list.get(2)
        self.assertEqual(number, 30)
        self.assertEqual(my_linked_list.length, 3)
        self.assertEqual(my_linked_list.head.value, 10)
        self.assertEqual(my_linked_list.tail.value, 30)

    def test_all(self):
        my_linked_list = LinkedList()
        my_linked_list.append(33)
        my_linked_list.pop()
        my_linked_list.append(12)
        my_linked_list.prepend(5)
        number = my_linked_list.get(1)
        self.assertEqual(number, 12)
        my_linked_list.pop()
        my_linked_list.append(77)
        number = my_linked_list.pop_first()
        self.assertEqual(my_linked_list.length, 1)
        self.assertEqual(my_linked_list.head.value, 77)
        self.assertEqual(my_linked_list.tail.value, 77)
        self.assertEqual(number, 5)


if __name__ == '__main__':
    unittest.main()
